### PR TITLE
ci: add secrets.CODECOV_TOKEN to codecov 

### PR DESCRIPTION
**Pull request by ramin**
Closes https://github.com/celestiaorg/nmt/issues/250

## Overview

@staheri14 noticed rate limiting in CI when sending data to CODECOV. This uses the org wide secret to ensure we are free from public usage/rate limiting

### CODE REVIEW

**Comment by ramin** [comment]
FYI @MSevey this is still being odd, can you verify the secret is available here and i believe there might be some admin on the codecov side maybe, see: https://github.com/celestiaorg/nmt/actions/runs/9077675099/job/24943089833?pr=255#step:8:33

**Review by evan-forbes — DISMISSED** [review]

**Comment by rootulp** [comment]
> there might be some admin on the codecov side maybe

+1 per [this line](https://github.com/celestiaorg/nmt/actions/runs/9077675099/job/24943089833?pr=255#step:8:33) maybe we need to enable the NMT in CodeCov UI so I deactivated and activated the repo. 

I can't change the default branch context to `main` perhaps b/c we haven't had a successful CodeCov upload from `main` yet

Screenshot 2024-05-14 at 8 59 09 AM

**Review by staheri14 — APPROVED** [review]
Thanks @ramin!

**Comment by ramin** [comment]
@rootulp bumped the action version to @v4 and that took care of some stuff, seems like it fails on a "test coverage regression" which I assume is maybe it comparing head to wrong primary branch? Otherwise, whatever was acting wild stopped

**Review by evan-forbes — APPROVED** [review]

**Review by staheri14 — APPROVED** [review]

**Review by walldiss — APPROVED** [review]

**Review by rootulp — APPROVED** [review]

**Comment by staheri14** [comment]
Does anything hinder this PR from being merged?

**Comment by rootulp** [comment]
IMO no, I didn't hit merge b/c we usually let PR authors merge their own PRs but in this case, seems safe to merge it b/c it fixes CI for other PRs

**Pull request merged**
