### PR TITLE
Refactoring: Push(namespace.PrefixedData)->Push(namespace.ID, []byte)

### PR DESCRIPTION
**Pull request by liamsi**
for details see: https://github.com/celestiaorg/nmt/issues/55 (particularly: https://github.com/celestiaorg/nmt/issues/55#issuecomment-1118931841)

closes: #55

### CODE REVIEW

**Comment by liamsi** [comment]
Note that due to the copy: https://github.com/celestiaorg/nmt/pull/56/checks?check_run_id=6312183477
image

**Review by evan-forbes — APPROVED** [review]
LGTM :+1: 

everytime I come to this repo, I'm always impressed with the test coverage and benchmarks etc. @liamsi 's work a long time ago is still paying dividends

also, one day we will stop changing the API for `Push` lolol

**Review by Wondertan — COMMENTED** [review]
@liamsi, One mid-level thing. We shouldn't pass the visitor the result of the append of nid+data and data only, or we should pass both as separate params as well.

Or just rework Visitor API completely, as we discussed 😅

**Comment by liamsi** [comment]
>  or we should pass both as separate params as well.

Yeah, that is what I thought as well but after we chatted about it it seemed not necessary and I didn't think about it further. Can you open an issue with the proposed method signature? I'll do a quick follow-up PR in the next few days.

**Pull request closed without merging**
